version: "3.1"

services:
  joomla:
    image: joomla:3.9.28
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: kiran12345

  joomladb:
    image: mysql:5.6
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: kiran12345
