name: PHPCS CI/CD Implementation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout code
        uses: actions/checkout@v3

      - name: Start Containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Setup php
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "7.1.3"

      - name: Setup Composer
        uses: "ramsey/composer-install@v2"

      - name: Install the libraries required
        run: composer install

      # - name: Run code sniffer and auto formatter
      #   run: ./site/vendor/bin/phpcs --standard=PSR12 ./

      - name: Build a package for installation
        run: zip -r ./install_extension.zip ./admin ./language ./plugin ./site dropbox.xml script.php

      - name: Copy package file inside the test folder
        run: cp install_extension.zip ./tests/e2e/filesForUpload
      
      - name: Install node required
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install dependencies and complete setup for Joomla
        run: |
          cd tests/e2e/
          npm i
          node installJoomla.js
          pwd && ls
          cd ..
          pwd && ls
          cd ..
          pwd && ls

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
