name: Playwright CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Chekout code
        uses: actions/checkout@v3

      - name: Install node required 
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      
      - name: Install node dependencies
        run: npm i

      - name: change a file
        run: node runMe.js
      
      - name: Commit files changed by tool
        if: always()
        run: |
          git config --global user.name 'Kiran Adhikari'
          git config --global user.email 'kiranadh1452@gmail.com'
          git add .
          git commit -m "[Robot]Automated commit 12"
          git pull --rebase https://github.com/kiranadh1452/composer-php-gAction.git ${{ github.head_ref }}
          git push https://github.com/kiranadh1452/composer-php-gAction.git HEAD:${{ github.head_ref }}

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down
